# --- Enabling fzf
# I installed based on README

# --- Aliases

# For monitoring my jobs in a slurm queue
alias sw='watch -n 1 squeue --user={my_username}'
# Aliases for ssh connections (need to set up keys for this)
alias sshGTI{server}='ssh krozgonyi@{server_ip_address}' # I am not putting the actual IP addresses here
# Alias for LaTeX compiler script so I can run it from anywhere (use it with the -c switch)
alias latex_compiler="$HOME/dotfiles/scripts/latex_compiler.sh"
# Alias for lazygit
alias lg='lazygit'
# Alias for init_tmux script
alias init_tmux="$HOME/dotfiles/scripts/init_general_tmux_session.sh"

# --- Overwrite the bash shell prompt by adding []:
OLD_PS1=$PS1
PS1="\[\e[1m\][\[\e[0m\]${OLD_PS1::-3}\[\e[1m\]]\[\e[0m\]$ "


